### ISSUE TITLE
python tutorial.py returns ImportError: No module named airflow

### ISSUE THREAD

**Issue by okihayashi** [aws/aws-mwaa-local-runner#148]
I wanted to execute the 'DAG Loader Test' described in the [official airflow doc](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#testing-a-dag) that is simply executing
```
python your-dag-file.py
```

Here I executed below to do the same but it returns import error.
```
$ docker-compose -f docker/docker-compose-local.yml exec -- local-runner /entrypoint.sh python dags/tutorial.py

Traceback (most recent call last):
  File "dags/tutorial.py", line 5, in <module>
    from airflow import DAG
ImportError: No module named airflow
```

This must be the same thing, but executing `python dags/tutorial.py` in the docker command line also returns the same result.
```
[airflow@a8b8c9755cf7 ~]$ python dags/tutorial.py 
Traceback (most recent call last):
  File "dags/tutorial.py", line 5, in <module>
    from airflow import DAG
ImportError: No module named airflow
```

Does something needs to be added to `docker-compose-local.yml` or other configuration files?
It would be very appreciated if anyone can give me some advice. thanks.

**Comment by okihayashi** [comment]
It was just because `python` command in the docker env created by mwaa-local-runner is executing `python2`.
