### ISSUE TITLE
Not able to install GDAL(3.5.1) in MWAA

### ISSUE THREAD

**Issue by SurajitChowbey** [aws/aws-mwaa-local-runner#157]
versions
- airflow = 2.2.2
- python = 3.7

requirenment file - 
[requirements.txt](https://github.com/aws/aws-mwaa-local-runner/files/9478044/requirements.txt)

here the error log - 
[error_log.txt](https://github.com/aws/aws-mwaa-local-runner/files/9478133/error_log.txt)

Looking forward to any probable solution here.
Thanks.

**Comment by john-jac** [comment]
Note that MWAA, and by extension local-runner, only provide user-level access. It's possible that the library is trying to build or run something that requires elevated permissions.  Recommend running the workload that runs this in an external container such as ECS or EKS.

**Comment by adelenelai** [comment]
@john-jac Hi, would you mind explaining in more detail what you mean by how to run in ECS or EKS? Or any other workarounds?

I too am trying to install gdal 3.6.3 on aws-mwaa-local-runner 2.5.1 and getting the same errors as @SurajitChowbey.


--------

Collecting gdal
  Downloading GDAL-3.6.3.tar.gz (757 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.9/757.9 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      WARNING: numpy not available!  Array support will not be enabled
      running egg_info
      creating /tmp/pip-pip-egg-info-gsv1c40o/GDAL.egg-info
      writing /tmp/pip-pip-egg-info-gsv1c40o/GDAL.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-gsv1c40o/GDAL.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-gsv1c40o/GDAL.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-gsv1c40o/GDAL.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-gsv1c40o/GDAL.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 87, in fetch_config
          p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      PermissionError: [Errno 13] Permission denied: 'gdal-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 188, in get_gdal_config
          return fetch_config(option, gdal_config=self.gdal_config)
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 90, in fetch_config
          raise gdal_config_error(e)
      __main__.gdal_config_error: [Errno 13] Permission denied: 'gdal-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 350, in <module>
          setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 308, in run
          self.find_sources()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
          mm.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 560, in run
          self.add_defaults()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
          sdist.add_defaults(self)
        File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 252, in add_defaults
          self._add_defaults_ext()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 306, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 109, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 255, in finalize_options
          gdaldir = self.get_gdal_config('prefix')
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 194, in get_gdal_config
          raise gdal_config_error(traceback_string + '\n' + msg)
      __main__.gdal_config_error: Traceback (most recent call last):
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 87, in fetch_config
          p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      PermissionError: [Errno 13] Permission denied: 'gdal-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 188, in get_gdal_config
          return fetch_config(option, gdal_config=self.gdal_config)
        File "/tmp/pip-install-u7i3qy93/gdal_6733b5ef77a14e42b9ef0fd9ae5770d0/setup.py", line 90, in fetch_config
          raise gdal_config_error(e)
      gdal_config_error: [Errno 13] Permission denied: 'gdal-config'

      Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by kw01sg** [comment]
Writing my solution here because I wasted one week on this and would never wish this on anyone else. What you need is a [startup script](https://docs.aws.amazon.com/mwaa/latest/userguide/using-startup-script.html) that installs `gdal` and `gdal-devel` runtime:

```bash
#!/bin/sh
# startup script for Amazon MWAA
# https://docs.aws.amazon.com/mwaa/latest/userguide/using-startup-script.html

echo "Updating operating system"
sudo yum update -y
# epel is supported on amazon linux 2 but not amazon linux 2023, so we are screwed if they upgrade
sudo amazon-linux-extras install epel -y
sudo yum install -y which gdal gdal-devel
which gdal-config; gdal-config --version
```

For this to work with `./mwaa-local-env test-requirements`, you need to run startup before installing the requirements. Check out this pull request on how to modify the current codebase to do that: https://github.com/aws/aws-mwaa-local-runner/pull/261.

Something else I experienced was that certain versions of libraries in `requirements.txt` can cause a lot of problem, so you might want to keep it flexible. What I did was just removing versions of problematic libraries (in my case it was rasterio), doing a `./mwaa-local-env test-requirements`, and then updating `requirements.txt` with the version that was successfully installed.

**Comment by smohanty92** [comment]
@kw01sg Anything for 2023? I'm stuck on this as well

**Comment by kw01sg** [comment]
> @kw01sg Anything for 2023? I'm stuck on this as well

What's the issue that you are having? my library that you are not able to install?

**Comment by idanb11** [comment]
@smohanty92 , @kw01sg - I am also stuck with this and cannot use `aws-mwaa-local-runner` to test my packages.
I am getting the same error that was reported before:

```
WARNING:root:Failed to get options via gdal-config: [Errno 13] Permission denied: 'gdal-config'
      ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
```

Trying to add this to the startup.sh file didn't also help:

```
sudo amazon-linux-extras install epel -y
sudo yum install -y which gdal gdal-devel
which gdal-config; gdal-config --version
...
...
...
No match for argument: gdal
No match for argument: gdal-devel
Error: Unable to find a match: gdal gdal-devel
```

any solution for that?

GDAL is a dependency for rasterio package

**Comment by kw01sg** [comment]
@idanb11 can you try a yum update?

**Comment by idanb11** [comment]
@kw01sg - thanks,
but yum updated doesn't help here

**Comment by kw01sg** [comment]
@idanb11 are you running the docker container on a macbook by chance. I remembered I had problem installing rasterio on an `amazonlinux:2023` container on a macbook, and had to spin up an EC2 to test the installation of rasterio. 

I just tested it on an ubuntu VM. I was able to install rasterio on a `amazonlinux:2023` container without install gdal.

**Comment by idanb11** [comment]
@kw01sg - yes, exactly.
I am using docker on mac with m2 processor

**Comment by kw01sg** [comment]
@idanb11 are you able to spin up a VM or an EC2 instance for testing? you should find that you are able to install rasterio in the mwaa container even without install gdal in the startup script
