### ISSUE TITLE
invalid login on initial setup

### ISSUE THREAD

**Issue by rnawhale** [aws/aws-mwaa-local-runner#300]
Hello,

When I follow the README to setup aws-mwaa-local-runner, I found that I can't login the airflow UI on localhost:8080. It says "invalid login. Please try again"
I was trying to reset the DB and it raised config exception like:

```
$ docker exec -it 9f4c2f949561 /bin/bash
[airflow@9f4c2f949561 ~]$ airflow resetdb
Traceback (most recent call last):
  File "/usr/local/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/__init__.py", line 42, in <module>
    from airflow import settings
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/settings.py", line 37, in <module>
    from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 1784, in <module>
    conf.validate()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 340, in validate
    self._validate_config_dependencies()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 452, in _validate_config_dependencies
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: error: sqlite C library version too old (< 3.15.0). See https://airflow.apache.org/docs/apache-airflow/2.5.1/howto/set-up-database.html#setting-up-a-sqlite-database
```

**Comment by mjsqu** [comment]
https://github.com/aws/aws-mwaa-local-runner/blob/v2.6.3/docker/config/.env.localrunner#L8

DEFAULT_PASSWORD="test"

So the password is test, but with double quotes
