### ISSUE TITLE
Configuring the AWS role for the airflow workers  botocore.exceptions.NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by AndrewKL** [aws/aws-mwaa-local-runner#43]
What is the correct way to configure the AWS credentials for the workers?

```
[2021-08-23 23:18:53,661] {{glue.py:112}} ERROR - Failed to run aws glue job, error: Unable to locate credentials
[2021-08-23 23:18:53,661] {{taskinstance.py:1482}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 121, in execute
    glue_job_run = glue_job.initialize_job(self.script_args)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 108, in initialize_job
    job_name = self.get_or_create_glue_job()
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 166, in get_or_create_glue_job
    get_job_response = glue_client.get_job(JobName=self.job_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 663, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 162, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 373, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by AndrewKL** [comment]
came up with a modification to copy the local ~/.aws/credentials file to the docker image

```
diff --git a/docker/docker-compose-local.yml b/docker/docker-compose-local.yml
index 054ab70..97dc2ab 100644
--- a/docker/docker-compose-local.yml
+++ b/docker/docker-compose-local.yml
@@ -28,6 +28,7 @@ services:
         volumes:
             - ${PWD}/dags:/usr/local/airflow/dags
             - ${PWD}/plugins:/usr/local/airflow/plugins
+            - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
         ports:
             - "8080:8080"
         command: local-runner
diff --git a/docker/docker-compose-resetdb.yml b/docker/docker-compose-resetdb.yml
index bcc9fe3..a02e803 100644
--- a/docker/docker-compose-resetdb.yml
+++ b/docker/docker-compose-resetdb.yml
@@ -27,6 +27,7 @@ services:
         volumes:
             - ${PWD}/dags:/usr/local/airflow/dags
             - ${PWD}/plugins:/usr/local/airflow/plugins
+            - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
         ports:
             - "8080:8080"
         command: resetdb
diff --git a/docker/docker-compose-sequential.yml b/docker/docker-compose-sequential.yml
index d25ce63..66e33bd 100644
--- a/docker/docker-compose-sequential.yml
+++ b/docker/docker-compose-sequential.yml
@@ -13,6 +13,7 @@ services:
         volumes:
             - ${PWD}/dags:/usr/local/airflow/dags
             - ${PWD}/plugins:/usr/local/airflow/plugins
+            - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
         ports:
             - "8080:8080"
         command: webserver

```

**Comment by KarthikRajashekaran** [comment]
@AndrewKL I mounted the /.aws/credentials as you mentioned but was still not able to connect to aws from within mwaa docker

**Comment by john-jac** [comment]
Please use ENV: https://github.com/aws/aws-mwaa-local-runner/pull/149

**Comment by rahulsing** [comment]
You can use the below compose file. Added line 23 and 33 to use Local AWS profile with the MWAA Local Runner Container by mounting local .aws folder.

https://github.com/rahulsing/aws-mwaa-local-runner/blob/v2.10.3/docker/docker-compose-local.yml
