### ISSUE TITLE
ModuleNotFoundError: No module named 'airflow.models.BaseOperator'

### ISSUE THREAD

**Issue by KarthikRajashekaran** [aws/aws-mwaa-local-runner#54]
I am running in aws-mwaa-local-runner
I wrote custom operator as below,not sure why it says no module found

```
import os
import sys
import csv
import tempfile
import logging
from contextlib import closing
from io import BytesIO, TextIOWrapper, BufferedRandom
from airflow.models.baseoperator import BaseOperator
from airflow.hooks.S3_hook import S3Hook
from airflow.contrib.hooks.snowflake_hook import SnowflakeHook
from utils.files import is_gz_compressed, compress_gz

logger = logging.getLogger(__name__)


class BaseUploadToS3(BaseOperator):
    """Extract data and compress to gzip format and upload to S3 location with s3_key
        Parameters
       ***************
```

But got below error

```

Broken DAG: [/usr/local/airflow/dags/a_dag.py] Traceback (most recent call last):
  File "/usr/local/airflow/dags/a_dag.py", line 8, in <module>
    from custom_operators.mssql_to_s3_operator import MsSqlToS3Operator
  File "/usr/local/airflow/dags/custom_operators/mssql_to_s3_operator.py", line 3, in <module>
    from airflow.models.BaseOperator import BaseOperator
ModuleNotFoundError: No module named 'airflow.models.BaseOperator'
```

When I checked inside the docker with python3
```
[airflow@6902213e0fbe ~]$ clear
[airflow@6902213e0fbe ~]$ python3
Python 3.7.10 (default, Jun  3 2021, 00:02:01)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from airflow.models.BaseOperator import BaseOperator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'airflow.models.BaseOperator'
>>>
```

**Comment by Melkeydev** [comment]
@KarthikRajashekaran What was the solution?
