### ISSUE TITLE
ERROR - No module named 'celery_config' when triggering a separate task in Airflow on Docker

### ISSUE THREAD

**Issue by alexmolodchikov** [aws/aws-mwaa-local-runner#61]
Deployment details
Running deployment on Docker for Local MWAA
aws-mwaa-local-runner:
https://github.com/aws/aws-mwaa-local-runner

### What happened
When triggering a single task instance through the UI (on demand), as soon as I click Run I get an error "Ooops!
Something bad has happened."

### Here is the stack trace:

```
local-runner_1  | /usr/local/lib/python3.7/site-packages/airflow/configuration.py:361 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.
local-runner_1  | [2021-10-22 05:21:40,118] {{configuration.py:484}} ERROR - No module named 'celery_config'
local-runner_1  | [2021-10-22 05:21:40,124] {{app.py:1892}} ERROR - Exception on /run [POST]
local-runner_1  | Traceback (most recent call last):
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 482, in getimport
local-runner_1  |     return import_string(full_qualified_path)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
local-runner_1  |     module = import_module(module_path)
local-runner_1  |   File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
local-runner_1  |     return _bootstrap._gcd_import(name[level:], package, level)
local-runner_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
local-runner_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
local-runner_1  |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
local-runner_1  | ModuleNotFoundError: No module named 'celery_config'
local-runner_1  | 
local-runner_1  | During handling of the above exception, another exception occurred:
local-runner_1  | 
local-runner_1  | Traceback (most recent call last):
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
local-runner_1  |     response = self.full_dispatch_request()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
local-runner_1  |     rv = self.handle_user_exception(e)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
local-runner_1  |     reraise(exc_type, exc_value, tb)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
local-runner_1  |     raise value
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
local-runner_1  |     rv = self.dispatch_request()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
local-runner_1  |     return self.view_functions[rule.endpoint](**req.view_args)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/auth.py", line 51, in decorated
local-runner_1  |     return func(*args, **kwargs)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/decorators.py", line 72, in wrapper
local-runner_1  |     return f(*args, **kwargs)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 1525, in run
local-runner_1  |     from airflow.executors.celery_executor import CeleryExecutor
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 72, in <module>
local-runner_1  |     celery_configuration = conf.getimport('celery', 'celery_config_options')
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 486, in getimport
local-runner_1  |     f'The object could not be loaded. Please check "{key}" key in "{section}" section. '
local-runner_1  | airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "celery_config_options" key in "celery" section. Current value: "celery_config.CUSTOM_CELERY_CONFIG".
```

### What you expected to happen
single task is triggered on-demand and running

How to reproduce
Start Apache airflow locally in docker environment
Create a sample DAG
Go into Graph View
Click on the Task Instance
Click Run

It looks like a environment issue,
This option is incorrect:
https://github.com/aws/aws-mwaa-local-runner/blob/9deba415c94fee8443508e466709d35dbcde122c/docker/config/airflow.cfg#L643

Here is default value:
[airflow/airflow/config_templates/default_airflow.cfg](https://github.com/apache/airflow/blob/1159133040b3513bcc88921823fa001e9773276d/airflow/config_templates/default_airflow.cfg#L792)

**Comment by pieterhameete** [comment]
Hey. We are also running into this issue. Please let us know if you find a fix for this. 

We are also looking into it and will do the same.

**Comment by john-jac** [comment]
Local-runner is not using celery.  Please confirm if you're seeing this in 2.2.2 (latest version)

**Comment by vipulneo** [comment]
Hi,
Still facing the same issue with local runner. 
`ERROR - No module named 'celery_config'
aws-mwaa-local-runner-2_2-local-runner-1  | [2022-11-09 00:41:47,438] {{app.py:1892}} ERROR - Exception on /run [POST]
aws-mwaa-local-runner-2_2-local-runner-1  | Traceback (most recent call last):
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 482, in getimport
aws-mwaa-local-runner-2_2-local-runner-1  |     return import_string(full_qualified_path)
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
aws-mwaa-local-runner-2_2-local-runner-1  |     module = import_module(module_path)
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
aws-mwaa-local-runner-2_2-local-runner-1  |     return _bootstrap._gcd_import(name[level:], package, level)
aws-mwaa-local-runner-2_2-local-runner-1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
aws-mwaa-local-runner-2_2-local-runner-1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
aws-mwaa-local-runner-2_2-local-runner-1  |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
aws-mwaa-local-runner-2_2-local-runner-1  | ModuleNotFoundError: No module named 'celery_config'
aws-mwaa-local-runner-2_2-local-runner-1  | 
aws-mwaa-local-runner-2_2-local-runner-1  | During handling of the above exception, another exception occurred:
aws-mwaa-local-runner-2_2-local-runner-1  | 
aws-mwaa-local-runner-2_2-local-runner-1  | Traceback (most recent call last):
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
aws-mwaa-local-runner-2_2-local-runner-1  |     response = self.full_dispatch_request()
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
aws-mwaa-local-runner-2_2-local-runner-1  |     rv = self.handle_user_exception(e)
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
aws-mwaa-local-runner-2_2-local-runner-1  |     reraise(exc_type, exc_value, tb)
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
aws-mwaa-local-runner-2_2-local-runner-1  |     raise value
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
aws-mwaa-local-runner-2_2-local-runner-1  |     rv = self.dispatch_request()
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
aws-mwaa-local-runner-2_2-local-runner-1  |     return self.view_functions[rule.endpoint](**req.view_args)
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/auth.py", line 51, in decorated
aws-mwaa-local-runner-2_2-local-runner-1  |     return func(*args, **kwargs)
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/decorators.py", line 72, in wrapper
aws-mwaa-local-runner-2_2-local-runner-1  |     return f(*args, **kwargs)
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 1536, in run
aws-mwaa-local-runner-2_2-local-runner-1  |     from airflow.executors.celery_executor import CeleryExecutor
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 72, in <module>
aws-mwaa-local-runner-2_2-local-runner-1  |     celery_configuration = conf.getimport('celery', 'celery_config_options')
aws-mwaa-local-runner-2_2-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 486, in getimport
aws-mwaa-local-runner-2_2-local-runner-1  |     f'The object could not be loaded. Please check "{key}" key in "{section}" section. '
aws-mwaa-local-runner-2_2-local-runner-1  | airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "celery_config_options" key in "celery" section. Current value: "celery_config.CUSTOM_CELERY_CONFIG".`

**Comment by gwerbin-tive** [comment]
I can reproduce this error reliably with `amazon/mwaa-local:2.2.2`:

```none
aws-mwaa-local-runner-222-local-runner-1  | [2022-12-05 23:48:45,240] {{configuration.py:484}} ERROR - No module named 'celery_config'
aws-mwaa-local-runner-222-local-runner-1  | [2022-12-05 23:48:45,240] {{app.py:1892}} ERROR - Exception on /run [POST]
aws-mwaa-local-runner-222-local-runner-1  | Traceback (most recent call last):
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 482, in getimport
aws-mwaa-local-runner-222-local-runner-1  |     return import_string(full_qualified_path)
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
aws-mwaa-local-runner-222-local-runner-1  |     module = import_module(module_path)
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
aws-mwaa-local-runner-222-local-runner-1  |     return _bootstrap._gcd_import(name[level:], package, level)
aws-mwaa-local-runner-222-local-runner-1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
aws-mwaa-local-runner-222-local-runner-1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
aws-mwaa-local-runner-222-local-runner-1  |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
aws-mwaa-local-runner-222-local-runner-1  | ModuleNotFoundError: No module named 'celery_config'
aws-mwaa-local-runner-222-local-runner-1  | 
aws-mwaa-local-runner-222-local-runner-1  | During handling of the above exception, another exception occurred:
aws-mwaa-local-runner-222-local-runner-1  | 
aws-mwaa-local-runner-222-local-runner-1  | Traceback (most recent call last):
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
aws-mwaa-local-runner-222-local-runner-1  |     response = self.full_dispatch_request()
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
aws-mwaa-local-runner-222-local-runner-1  |     rv = self.handle_user_exception(e)
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
aws-mwaa-local-runner-222-local-runner-1  |     reraise(exc_type, exc_value, tb)
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
aws-mwaa-local-runner-222-local-runner-1  |     raise value
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
aws-mwaa-local-runner-222-local-runner-1  |     rv = self.dispatch_request()
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
aws-mwaa-local-runner-222-local-runner-1  |     return self.view_functions[rule.endpoint](**req.view_args)
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/auth.py", line 51, in decorated
aws-mwaa-local-runner-222-local-runner-1  |     return func(*args, **kwargs)
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/decorators.py", line 72, in wrapper
aws-mwaa-local-runner-222-local-runner-1  |     return f(*args, **kwargs)
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 1536, in run
aws-mwaa-local-runner-222-local-runner-1  |     from airflow.executors.celery_executor import CeleryExecutor
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 72, in <module>
aws-mwaa-local-runner-222-local-runner-1  |     celery_configuration = conf.getimport('celery', 'celery_config_options')
aws-mwaa-local-runner-222-local-runner-1  |   File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 486, in getimport
aws-mwaa-local-runner-222-local-runner-1  |     f'The object could not be loaded. Please check "{key}" key in "{section}" section. '
aws-mwaa-local-runner-222-local-runner-1  | airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "celery_config_option
s" key in "celery" section. Current value: "celery_config.CUSTOM_CELERY_CONFIG".
```

**Comment by akashg90** [comment]
Were you able to fix this issue?
