### ISSUE TITLE
Airflow Database Fails to be Created v2.02

### ISSUE THREAD

**Issue by ea-chodgson** [aws/aws-mwaa-local-runner#68]
After running ./mwaa-local-env build-image, I'm getting an error on start up where it can't find a database in postgres called "airflow"

**Build Output:**
[+] Building 467.8s (18/18) FINISHED                                                                                            
 => [internal] load build definition from Dockerfile                                                                       0.0s
 => => transferring dockerfile: 1.13kB                                                                                     0.0s
 => [internal] load .dockerignore                                                                                          0.0s
 => => transferring context: 2B                                                                                            0.0s
 => [internal] load metadata for public.ecr.aws/amazonlinux/amazonlinux:latest                                             1.3s
 => [ 1/13] FROM public.ecr.aws/amazonlinux/amazonlinux@sha256:69a7e4782be3dc25f610582d6ad7a88d1db7db08f27248153efe726ea6  4.5s
 => => resolve public.ecr.aws/amazonlinux/amazonlinux@sha256:69a7e4782be3dc25f610582d6ad7a88d1db7db08f27248153efe726ea607  0.0s
 => => sha256:69a7e4782be3dc25f610582d6ad7a88d1db7db08f27248153efe726ea6077bbf 770B / 770B                                 0.0s
 => => sha256:cc86ae1a38753902f280ccd88a727370c6b3b258c220a9cea97098bfab559e47 529B / 529B                                 0.0s
 => => sha256:72203fadaf3a1e1836f88dafe18ba7413381e5d623aa0167689e204d00e8be4c 1.49kB / 1.49kB                             0.0s
 => => sha256:74f9a6be36f3bc3bf6041c40376d548e3a8b720a0455674b19e9174a9e567078 63.69MB / 63.69MB                           2.6s
 => => extracting sha256:74f9a6be36f3bc3bf6041c40376d548e3a8b720a0455674b19e9174a9e567078                                  1.7s
 => [internal] load build context                                                                                          0.0s
 => => transferring context: 58.52kB                                                                                       0.0s
 => [ 2/13] COPY script/bootstrap.sh /bootstrap.sh                                                                         0.1s
 => [ 3/13] COPY script/systemlibs.sh /systemlibs.sh                                                                       0.0s
 => [ 4/13] COPY config/constraints.txt /constraints.txt                                                                   0.0s
 => [ 5/13] COPY config/requirements.txt /requirements.txt                                                                 0.0s
 => [ 6/13] RUN chmod u+x /systemlibs.sh && /systemlibs.sh                                                                36.2s
 => [ 7/13] RUN chmod u+x /bootstrap.sh && /bootstrap.sh                                                                 420.9s
 => [ 8/13] COPY script/entrypoint.sh /entrypoint.sh                                                                       0.0s
 => [ 9/13] COPY config/airflow.cfg /usr/local/airflow/airflow.cfg                                                         0.0s
 => [10/13] COPY config/webserver_config.py /usr/local/airflow/webserver_config.py                                         0.0s
 => [11/13] RUN chown -R airflow: /usr/local/airflow                                                                       0.1s
 => [12/13] RUN chmod +x /entrypoint.sh                                                                                    0.2s
 => [13/13] WORKDIR /usr/local/airflow                                                                                     0.0s
 => exporting to image                                                                                                     4.4s
 => => exporting layers                                                                                                    4.4s
 => => writing image sha256:106708a74262919fcffda619d0ad72fbd2133b162980f496a4ec47be53d8a8ca                               0.0s
 => => naming to docker.io/amazon/mwaa-local:2.0.2      

**Run Output:**
 aws-mwaa-local-runner git:(main) ✗ ./mwaa-local-env start
[+] Running 10/10
 ⠿ postgres Pulled                                                                                                         4.5s
   ⠿ 9b3977197b4f Pull complete                                                                                            0.8s
   ⠿ 995a68b04f2b Pull complete                                                                                            0.8s
   ⠿ e8a8bdf2ee5e Pull complete                                                                                            0.9s
   ⠿ 1ebc4d347b54 Pull complete                                                                                            2.8s
   ⠿ 6b3dbdc5cac4 Pull complete                                                                                            2.9s
   ⠿ b1466ea51568 Pull complete                                                                                            2.9s
   ⠿ 9f0e4a4c8440 Pull complete                                                                                            2.9s
   ⠿ a8ca5f3c2a28 Pull complete                                                                                            3.0s
   ⠿ d29e603cee34 Pull complete                                                                                            3.0s
[+] Running 3/2
 ⠿ Network docker_default           Created                                                                                0.0s
 ⠿ Container docker_postgres_1      Created                                                                                0.1s
 ⠿ Container docker_local-runner_1  Created                                                                                0.0s
Attaching to local-runner_1, postgres_1
postgres_1      | 
postgres_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1      | 
postgres_1      | 2021-12-07 20:07:18.417 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1      | 2021-12-07 20:07:18.417 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1      | 2021-12-07 20:07:18.431 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1      | 2021-12-07 20:07:18.496 UTC [23] LOG:  database system was shut down at 2021-12-07 19:45:43 UTC
postgres_1      | 2021-12-07 20:07:18.522 UTC [1] LOG:  database system is ready to accept connections
postgres_1      | 2021-12-07 20:07:18.719 UTC [30] LOG:  incomplete startup packet
local-runner_1  | Installing requirements.txt
local-runner_1  | DB: postgresql+psycopg2://airflow:***@postgres:5432/airflow
local-runner_1  | [2021-12-07 20:07:20,906] {{db.py:684}} INFO - Creating tables
postgres_1      | 2021-12-07 20:07:20.913 UTC [31] FATAL:  database "airflow" does not exist
postgres_1      | 2021-12-07 20:07:20.935 UTC [32] FATAL:  database "airflow" does not exist
postgres_1      | 2021-12-07 20:07:20.942 UTC [33] FATAL:  database "airflow" does not exist
local-runner_1  | Traceback (most recent call last):
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
local-runner_1  |     return fn()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
local-runner_1  |     return _ConnectionFairy._checkout(self)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
local-runner_1  |     fairy = _ConnectionRecord.checkout(pool)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
local-runner_1  |     rec = pool._do_get()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
local-runner_1  |     return self._create_connection()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
local-runner_1  |     return _ConnectionRecord(self)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
local-runner_1  |     self.__connect(first_connect_check=True)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
local-runner_1  |     pool.logger.debug("Error on connect(): %s", e)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
local-runner_1  |     with_traceback=exc_tb,
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
local-runner_1  |     raise exception
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
local-runner_1  |     connection = pool._invoke_creator(self)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
local-runner_1  |     return dialect.connect(*cargs, **cparams)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
local-runner_1  |     return self.dbapi.connect(*cargs, **cparams)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
local-runner_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
local-runner_1  | psycopg2.OperationalError: FATAL:  database "airflow" does not exist
local-runner_1  | 
local-runner_1  | 
local-runner_1  | The above exception was the direct cause of the following exception:
local-runner_1  | 
local-runner_1  | Traceback (most recent call last):
local-runner_1  |   File "/usr/local/bin/airflow", line 8, in <module>
local-runner_1  |     sys.exit(main())
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/__main__.py", line 40, in main
local-runner_1  |     args.func(args)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
local-runner_1  |     return func(*args, **kwargs)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/db_command.py", line 31, in initdb
local-runner_1  |     db.initdb()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 559, in initdb
local-runner_1  |     upgradedb()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 694, in upgradedb
local-runner_1  |     command.upgrade(config, 'heads')
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 294, in upgrade
local-runner_1  |     script.run_env()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 490, in run_env
local-runner_1  |     util.load_python_file(self.dir, "env.py")
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
local-runner_1  |     module = load_module_py(module_id, path)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 182, in load_module_py
local-runner_1  |     spec.loader.exec_module(module)
local-runner_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
local-runner_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/migrations/env.py", line 108, in <module>
local-runner_1  |     run_migrations_online()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/migrations/env.py", line 91, in run_migrations_online
local-runner_1  |     with connectable.connect() as connection:
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
local-runner_1  |     return self._connection_cls(self, **kwargs)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
local-runner_1  |     else engine.raw_connection()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2370, in raw_connection
local-runner_1  |     self.pool.unique_connection, _connection
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
local-runner_1  |     e, dialect, self
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
local-runner_1  |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
local-runner_1  |     raise exception
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
local-runner_1  |     return fn()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
local-runner_1  |     return _ConnectionFairy._checkout(self)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
local-runner_1  |     fairy = _ConnectionRecord.checkout(pool)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
local-runner_1  |     rec = pool._do_get()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
local-runner_1  |     return self._create_connection()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
local-runner_1  |     return _ConnectionRecord(self)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
local-runner_1  |     self.__connect(first_connect_check=True)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
local-runner_1  |     pool.logger.debug("Error on connect(): %s", e)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
local-runner_1  |     with_traceback=exc_tb,
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
local-runner_1  |     raise exception
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
local-runner_1  |     connection = pool._invoke_creator(self)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
local-runner_1  |     return dialect.connect(*cargs, **cparams)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
local-runner_1  |     return self.dbapi.connect(*cargs, **cparams)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
local-runner_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
local-runner_1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "airflow" does not exist
local-runner_1  | 
local-runner_1  | (Background on this error at: http://sqlalche.me/e/13/e3q8)
postgres_1      | 2021-12-07 20:07:21.383 UTC [34] FATAL:  database "airflow" does not exist
local-runner_1  | [2021-12-07 20:07:21,384] {{cli_action_loggers.py:105}} WARNING - Failed to log action with (psycopg2.OperationalError) FATAL:  database "airflow" does not exist

**So far I've tried:**
- Clearing the Docker Cache and repulling the repo
- The solution to issue #16 
- Manually adding the "airflow" db to postgres (I ran into issues logging into postgres when I tried to do this)

OS is Mac Big Sur with M1

**Comment by ea-chodgson** [comment]
Finally was able to force it to work: by running sudo docker exec -it docker_postgres_1 createdb -h localhost -U airflow airflow.

I'm not sure why it didn't get created initially. May be something to investigate.
